apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grp07eq1-role
  namespace: grp07eq1-namespace
rules:
- apiGroups:
  - ''
  - extensions
  - apps
  - networking.k8s.io
  resources:
  - deployments
  - pods
  - pods/log
  - pods/portforward
  - pods/exec
  - secrets
  - services
  - configmaps
  - events
  - replicasets
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
