apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarket-api
  # namespace: group-01   # or another namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermarket-api
  template:
    metadata:
      labels:
        app: supermarket-api
    spec:
      containers:
      - name: supermarket-api
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"