name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/supermarket-api

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: .

  build-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-test.result == 'success' }}
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          echo "tag=${SHA_TAG}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

  deploy-to-k8s:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install IBM Cloud CLI and Kubernetes plugin
        run: |
          # Install IBM Cloud CLI
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

          # Install the container-service (Kubernetes) plugin
          ibmcloud plugin install container-service -f

          # Log in
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r ${{ secrets.IBM_REGION }}

          # Configure kubeconfig
          ibmcloud ks cluster config --cluster ${{ secrets.IBM_CLUSTER_ID }}

          # Set KUBECONFIG environment variable
          export KUBECONFIG=$(ls ~/.bluemix/plugins/container-service/clusters/*/kube-config-*.yml | head -n 1)

      # one-time setup (safe to reapply)
      - name: Apply namespace and RBAC
        run: |
          kubectl apply -f k8s/setup/namespace.yaml
          kubectl apply -f k8s/setup/quota.yaml
          kubectl apply -f k8s/setup/role.yaml
          kubectl apply -f k8s/setup/role_binding.yaml

      # deploy the app with dynamic image tag
      - name: Deploy app
        run: |
          NAMESPACE=$(kubectl get -f k8s/setup/namespace.yaml -o jsonpath='{.metadata.name}')
          IMAGE=${{ env.IMAGE_NAME }}:${{ needs.build-push-image.outputs.tag }}
          
          # Substitute image and apply deployment in the correct namespace
          sed "s|DOCKER_IMAGE_PLACEHOLDER|$IMAGE|" k8s/base/deployment.yaml | kubectl apply -f - -n $NAMESPACE

          # Apply service in the same namespace
          kubectl apply -f k8s/base/service.yaml -n $NAMESPACE